[window]
decorations = "none"

[font]
size = 9.0  # Adjust this to change font size

[font.normal]
family = "Fira Code"
style = "Regular"

[font.bold]
family = "Fira Code"
style = "Bold"

[font.italic]
family = "Fira Code"
style = "Italic"

